# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PowerShell for the win!
email: me@david-obrien.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidobrien1985.github.io" # the base hostname & protocol for your site
twitter_username: david_obrien
github_username:  davidobrien1985

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-mentions
# - pygments.rb
 - redcarpet

exclude:
 - .gitignore
 - .git